### ISSUE TITLE
3 MbUnit tests are failing

### ISSUE THREAD

**Issue by alex-bogomaz** [fsprojects/FsUnit#79]
following 3 MbUnit tests are failing:
1) Seq with 1 item should fail to have Count 1
2) Seq with 1 item should fail to have Length 1 
3) shouldFaild should throw an exception 

here is the complete execution log for failing tests:

```
FsUnit.MbUnit.Test 
Passed0Failed3Inconclusive or Skipped0
Duration: 0.393s, Assertions: 6.
File: D:\My\Projects\tmp\2\FsUnit-master\tests\FsUnit.MbUnit.Test\bin\Release\FsUnit.MbUnit.Test.DLL
CodeBase: D:\My\Projects\tmp\2\FsUnit-master\tests\FsUnit.MbUnit.Test\bin\Release\FsUnit.MbUnit.Test.DLL
Version: 0.0.0.0
Framework: MbUnit v3.4 build 11
have Count tests 
Passed0Failed1Inconclusive or Skipped0
Duration: 0.326s, Assertions: 2.
Seq with 1 item should fail to have Count 1 

Duration: 0.296s, Assertions: 2.
An exception occurred while verifying an assertion.

System.ArgumentException: Property Count was not found
Parameter name: name
ParamName: name
   at FsUnit.CustomMatchers.op_Dynamic[Source,Result](Source this, String name) in D:\My\Projects\tmp\2\FsUnit-master\src\FsUnit.Xunit\CustomMatchers.fs:line 118
   at FsUnit.CustomMatchers.haveCount@123.Invoke(Object arg) in D:\My\Projects\tmp\2\FsUnit-master\src\FsUnit.Xunit\CustomMatchers.fs:line 123
   at NHamcrest.CustomMatcher`1.Matches(T item) in C:\Documents and Settings\Graham\My Documents\NHamcrest\NHamcrest\CustomMatcher.cs:line 28

   at <StartupCode$FsUnit-MbUnit-Test>.$HaveCountTests.Seq with 1 item should fail to have Count 1@32.Invoke(Unit unitVar0) in D:\My\Projects\tmp\2\FsUnit-master\tests\FsUnit.MbUnit.Test\haveCountTests.fs:line 32
   at FsUnit.CustomMatchers.throw@25.Invoke(Object arg) in D:\My\Projects\tmp\2\FsUnit-master\src\FsUnit.Xunit\CustomMatchers.fs:line 29
   at NHamcrest.CustomMatcher`1.Matches(T item) in C:\Documents and Settings\Graham\My Documents\NHamcrest\NHamcrest\CustomMatcher.cs:line 28
   at FsUnit.Test.have Count tests.Seq with 1 item should fail to have Count 1() in D:\My\Projects\tmp\2\FsUnit-master\tests\FsUnit.MbUnit.Test\haveCountTests.fs:line 32

Expected System.ArgumentException

Expected : System.ArgumentException
But      : was <StartupCode$FsUnit-MbUnit-Test>.$HaveCountTests+Seq with 1 item should fail to have Count 1@32

   at FsUnit.Test.have Count tests.Seq with 1 item should fail to have Count 1() in D:\My\Projects\tmp\2\FsUnit-master\tests\FsUnit.MbUnit.Test\haveCountTests.fs:line 32

haveLength tests 
Passed0Failed1Inconclusive or Skipped0
Duration: 0.011s, Assertions: 2.
Seq with 1 item should fail to have Length 1 

Duration: 0.007s, Assertions: 2.
An exception occurred while verifying an assertion.

System.ArgumentException: Property Length was not found
Parameter name: name
ParamName: name
   at FsUnit.CustomMatchers.op_Dynamic[Source,Result](Source this, String name) in D:\My\Projects\tmp\2\FsUnit-master\src\FsUnit.Xunit\CustomMatchers.fs:line 118
   at FsUnit.CustomMatchers.haveLength@121.Invoke(Object arg) in D:\My\Projects\tmp\2\FsUnit-master\src\FsUnit.Xunit\CustomMatchers.fs:line 121
   at NHamcrest.CustomMatcher`1.Matches(T item) in C:\Documents and Settings\Graham\My Documents\NHamcrest\NHamcrest\CustomMatcher.cs:line 28

   at <StartupCode$FsUnit-MbUnit-Test>.$HaveLengthTests.Seq with 1 item should fail to have Length 1@45.Invoke(Unit unitVar0) in D:\My\Projects\tmp\2\FsUnit-master\tests\FsUnit.MbUnit.Test\haveLengthTests.fs:line 45
   at FsUnit.CustomMatchers.throw@25.Invoke(Object arg) in D:\My\Projects\tmp\2\FsUnit-master\src\FsUnit.Xunit\CustomMatchers.fs:line 29
   at NHamcrest.CustomMatcher`1.Matches(T item) in C:\Documents and Settings\Graham\My Documents\NHamcrest\NHamcrest\CustomMatcher.cs:line 28
   at FsUnit.Test.haveLength tests.Seq with 1 item should fail to have Length 1() in D:\My\Projects\tmp\2\FsUnit-master\tests\FsUnit.MbUnit.Test\haveLengthTests.fs:line 45

Expected System.ArgumentException

Expected : System.ArgumentException
But      : was <StartupCode$FsUnit-MbUnit-Test>.$HaveLengthTests+Seq with 1 item should fail to have Length 1@45

   at FsUnit.Test.haveLength tests.Seq with 1 item should fail to have Length 1() in D:\My\Projects\tmp\2\FsUnit-master\tests\FsUnit.MbUnit.Test\haveLengthTests.fs:line 45

shouldFail tests 
Passed0Failed1Inconclusive or Skipped0
Duration: 0.011s, Assertions: 2.
shouldFaild should throw an exception 

Duration: 0.008s, Assertions: 2.
Expected True
Method should fail

Expected : True
But      : was False

   at <StartupCode$FsUnit-MbUnit-Test>.$ShouldFailTests.shouldFaild should throw an exception@23.Invoke(Unit unitVar0) in D:\My\Projects\tmp\2\FsUnit-master\tests\FsUnit.MbUnit.Test\shouldFailTests.fs:line 23
   at FsUnit.CustomMatchers.throw@25.Invoke(Object arg) in D:\My\Projects\tmp\2\FsUnit-master\src\FsUnit.Xunit\CustomMatchers.fs:line 29
   at NHamcrest.CustomMatcher`1.Matches(T item) in C:\Documents and Settings\Graham\My Documents\NHamcrest\NHamcrest\CustomMatcher.cs:line 28
   at FsUnit.Test.shouldFail tests.shouldFaild should throw an exception() in D:\My\Projects\tmp\2\FsUnit-master\tests\FsUnit.MbUnit.Test\shouldFailTests.fs:line 23

Expected System.Exception

Expected : System.Exception
But      : was <StartupCode$FsUnit-MbUnit-Test>.$ShouldFailTests+shouldFaild should throw an exception@23

   at FsUnit.Test.shouldFail tests.shouldFaild should throw an exception() in D:\My\Projects\tmp\2\FsUnit-master\tests\FsUnit.MbUnit.Test\shouldFailTests.fs:line 23
```

**Comment by sergey-tihon** [comment]
@alex-bogomaz How do you run them?

Could you please help to automate it properly in https://github.com/fsprojects/FsUnit/blob/master/build.fsx

I have no idea how to execute them, that's why they may be broken and old version on NuGet

**Comment by alex-bogomaz** [comment]
i'm using Gallion bundle (Gallio.Icarus.exe)  downloaded from
https://code.google.com/p/mb-unit/

but now i realize that MbUnit version on Google code is quite old. They have new version on GitHub, so I'm gonna check against that version

**Comment by sergey-tihon** [comment]
@alex-bogomaz Do you know how we can automate execution of MbUnit tests ?

**Comment by alex-bogomaz** [comment]
still trying to figure out how to run them using FAKE.MbUnit....

**Comment by sergey-tihon** [comment]
@alex-bogomaz Any news?

@mausch Do you know how to run MbUnit tests from FAKE?

**Comment by mausch** [comment]
Ugh, I'm getting an entirely different error:

```
Gallio.Runtime.RuntimeException: Could not resolve component for service type 'Gallio.Runner.Projects.ITestProjectManager' because there do not appear to be any components registered and enabled for that service type.
   at Gallio.Runtime.Extensibility.RegistryServiceLocator.ResolveNonDisabledDescriptor(Type serviceType) in c:\Server\Projects\MbUnit v3\Work\src\Gallio\Gallio\Runtime\Extensibility\RegistryServiceLocator.s:line 197
   at Gallio.Runtime.Extensibility.RegistryServiceLocator.Resolve[TService]() in c:\Server\Projects\MbUnit v3\Work\src\Gallio\Gallio\Runtime\Extensibility\RegistryServiceLocator.cs:line 52
   at Gallio.Runner.TestLauncher.RunWithRuntime() in c:\Server\Projects\MbUnit v3\Work\src\Gallio\Gallio\Runner\TestLauncher.cs:line 513
   at Gallio.Runner.TestLauncher.Run() in c:\Server\Projects\MbUnit v3\Work\src\Gallio\Gallio\Runner\TestLauncher.cs:line 480
   at Fake.Gallio.Run(FSharpFunc`2 setParam, IEnumerable`1 assemblies) in C:\code\fake\src\app\Fake.Gallio\GallioHelper.fs:line 211
   at FSI_0005.Build.clo@144-15.Invoke(Unit _arg9) in c:\prg\FsUnit\build.fsx:line 145
   at Fake.TargetHelper.runSingleTarget(TargetTemplate`1 target) in C:\code\fake\src\app\FakeLib\TargetHelper.fs:line 484
````

**Comment by mausch** [comment]
Might be because FAKE.MbUnit depends on Gallio 3.3 while FsUnit uses Gallio/MbUnit 3.4.14

**Comment by sergey-tihon** [comment]
MbUnit has not been updated since 10/20/2014
These are no plans to update or release new versions for MbUnit
Related source code removed from the repo in #135
